CREATE TABLE IF NOT EXISTS "changelog_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "changelog_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_changelog" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"project_id" varchar(255) NOT NULL,
	"version" varchar(50) NOT NULL,
	"content" text NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "changelog_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_project" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"repository_url" varchar(255) NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"settings" text DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_template" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"project_id" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "changelog_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "changelog_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_account" ADD CONSTRAINT "changelog_account_user_id_changelog_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."changelog_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_changelog" ADD CONSTRAINT "changelog_changelog_project_id_changelog_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."changelog_project"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_post" ADD CONSTRAINT "changelog_post_created_by_changelog_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."changelog_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_project" ADD CONSTRAINT "changelog_project_created_by_changelog_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."changelog_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_session" ADD CONSTRAINT "changelog_session_user_id_changelog_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."changelog_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "changelog_template" ADD CONSTRAINT "changelog_template_project_id_changelog_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."changelog_project"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "changelog_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "changelog_project_id_idx" ON "changelog_changelog" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "changelog_version_idx" ON "changelog_changelog" USING btree ("version");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_by_idx" ON "changelog_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "changelog_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_created_by_idx" ON "changelog_project" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_repository_url_idx" ON "changelog_project" USING btree ("repository_url");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "changelog_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "template_project_id_idx" ON "changelog_template" USING btree ("project_id");